
name: iOS-ipa-build

on:
  workflow_dispatch:

jobs:
  build-ios:
    name: ðŸŽ‰ iOS Build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64
      - run: flutter pub get
        working-directory: frontend
      

      - run: pod repo update
        working-directory: frontend/ios

      - run: flutter build ios --release --no-codesign
        working-directory: frontend

      - run: mkdir Payload
        working-directory: frontend/build/ios/iphoneos

      - run: mv Runner.app/ Payload
        working-directory: frontend/build/ios/iphoneos

      - name: Zip output
        run: zip -qq -r -9 FlutterIpaExport.ipa Payload
        working-directory: frontend/build/ios/iphoneos

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-ipa
          path: frontend/build/ios/iphoneos/FlutterIpaExport.ipa
